### ISSUE TITLE
pdfScale doesn't preserve hyperlinks

### ISSUE THREAD

**Issue by psiccardi** [tavinus/pdfScale#14]
Using pdfscale to scale a page doesn't preserve hyperlinks.
Could you add the possibility to pass the "-dPrinted=false" parameter to gs?
Now i'm using this script with the addition of this parameter (i edited the script in my local machine) to achieve my goal. 
Anyway, nice work! This script saved me hours of life!

**Comment by tavinus** [comment]
Thanks for letting me know.  
I will try to add and test that soon.

**Comment by tavinus** [comment]
#### Possible solutions:
 - Ghostscript option: `-dPrinted=false`
 - Hyperref option "pdfa": `\usepackage[pdfa]{hyperref}`

#### More info:  
- https://www.ghostscript.com/doc/9.21/Use.htm
- https://tex.stackexchange.com/questions/245801/local-hyperlinks-broken-after-pdf-processing-with-ghostscript
- https://tex.stackexchange.com/questions/456896/set-the-print-flag-on-links-with-hyperref-to-preserve-them-with-ghostscript-9
  
#### Problems:
 - The `-dPrinted=false` ghostscript option will have the effect to drop print annotations.
 - The `pdfa hyperref` option is actually a bad idea: if used, when the PDF file is printed, the boxes around the links are printed, making the document less readable.
  
#### GS manual info
![image](https://user-images.githubusercontent.com/8039413/64738513-c5947f00-d4c5-11e9-9e3a-2d03cb34ecc2.png)
  
#### Conclusions
I will probably just set an optional flag for `dPrinted=false`.  
Still not sure what should be the default though.  
**What is more important? Preserving URLs or preserving print annotations?**

**Comment by tavinus** [comment]
Implemented on v2.4.9 ( https://github.com/tavinus/pdfScale/commit/e3d826d14ae245f8b1d127082b9054c800158dc9 )
  
Created parameter `--print-mode <screen|printer>` to control the `dPrinted` parameter on GS calls.  
  
Default behavior is unchanged, it is left empty which will use a print profile if there is an output file set (which we always do at this point).  
  
#### Otherwise
 - `--print-mode screen` > adds `-dPrinted=false` to calls
 - `--print-mode printer` > adds `-dPrinted` to calls (forces print mode)
  
Forcing print mode is kind of useless at this point, but can become useful in the future.  
  
Cheers!  
Gus
